//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFPTShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int IDRat { get; set; }
        public Nullable<int> IDCus { get; set; }
        public Nullable<int> IDPro { get; set; }
        public Nullable<int> Start { get; set; }
        public string Content { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
